version: '3.8'

services:
 # Our flask application
 web:
  build:
   context: .
   platform: linux/arm64/v8
  ports:
  - 2000:5000
  volumes:
  - ./:/app

 # Our mysql container
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
